Compile fixes for SoSceneManager::getBackgroundColor (SbColor4f version).

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -27105,6 +27105,76 @@ fi
 
 
 
+echo "$as_me:$LINENO: checking for SbColor4f SoSceneManager::getBackgroundColor" >&5
+echo $ECHO_N "checking for SbColor4f SoSceneManager::getBackgroundColor... $ECHO_C" >&6
+if test "${sim_cv_have_oiv_have_sbcolor4f_getbackgroundcolor+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <Inventor/SoSceneManager.h>
+int
+main ()
+{
+
+   SbColor4f col = SoSceneManager().getBackgroundColor();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  sim_cv_have_oiv_have_sbcolor4f_getbackgroundcolor=true
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+sim_cv_have_oiv_have_sbcolor4f_getbackgroundcolor=false
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $sim_cv_have_oiv_have_sbcolor4f_getbackgroundcolor" >&5
+echo "${ECHO_T}$sim_cv_have_oiv_have_sbcolor4f_getbackgroundcolor" >&6
+
+if $sim_cv_have_oiv_have_sbcolor4f_getbackgroundcolor; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SBCOLOR4F_GETBACKGROUNDCOLOR 1
+_ACEOF
+
+
+else
+  :
+fi
+
+
+
+
 echo "$as_me:$LINENO: checking for SoContextHandler class" >&5
 echo $ECHO_N "checking for SoContextHandler class... $ECHO_C" >&6
 if test "${sim_cv_have_oiv_have_socontexthandler+set}" = set; then
