Adapt to the new design of the SoAnyExamples module.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -621,7 +621,7 @@ fi
 
 if test ! -f ${srcdir}/examples/ChangeLog; then
   echo ""
-  echo "  You appear to have an old setup of the SoQe source repository."
+  echo "  You appear to have an old setup of the SoQt source repository."
   echo "  Parts of it have changed structurally, and you need to do the"
   echo "  following in the SoQt source directory:"
   echo ""
@@ -4125,51 +4125,27 @@ COMPONENTHEADER="Q_OBJECT"
 
 
 
+# Pass to examples/configure
+export GUI lGUI uGUI WIDGET EVENT COMPONENTHEADER
+
+# Pass to examples/configure
+HAVE_RENDERAREA=true
+HAVE_EXAMINERVIEWER=true
+HAVE_PLANEVIEWER=true
+HAVE_WALKVIEWER=false
+HAVE_FLYVIEWER=false
+export HAVE_RENDERAREA HAVE_EXAMINERVIEWER HAVE_PLANEVIEWER HAVE_WALKVIEWER HAVE_FLYVIEWER
 
 
-if true; then
-  HAVE_RENDERAREA_TRUE=
-  HAVE_RENDERAREA_FALSE='#'
-else
-  HAVE_RENDERAREA_TRUE='#'
-  HAVE_RENDERAREA_FALSE=
-fi
+# Pass to examples/configure.in
+EXTRA_CPPFLAGS=$SOQT_EXTRA_CPPFLAGS
+EXTRA_LDFLAGS=$SOQT_EXTRA_LDFLAGS
+EXTRA_LIBS=$SOQT_EXTRA_LIBS
+export EXTRA_CPPFLAGS EXTRA_LDFLAGS EXTRA_LIBS
+
+subdirs="examples"
 
 
-if true; then
-  HAVE_EXAMINERVIEWER_TRUE=
-  HAVE_EXAMINERVIEWER_FALSE='#'
-else
-  HAVE_EXAMINERVIEWER_TRUE='#'
-  HAVE_EXAMINERVIEWER_FALSE=
-fi
-
-
-if true; then
-  HAVE_PLANEVIEWER_TRUE=
-  HAVE_PLANEVIEWER_FALSE='#'
-else
-  HAVE_PLANEVIEWER_TRUE='#'
-  HAVE_PLANEVIEWER_FALSE=
-fi
-
-
-if false; then
-  HAVE_WALKVIEWER_TRUE=
-  HAVE_WALKVIEWER_FALSE='#'
-else
-  HAVE_WALKVIEWER_TRUE='#'
-  HAVE_WALKVIEWER_FALSE=
-fi
-
-
-if false; then
-  HAVE_FLYVIEWER_TRUE=
-  HAVE_FLYVIEWER_FALSE='#'
-else
-  HAVE_FLYVIEWER_TRUE='#'
-  HAVE_FLYVIEWER_FALSE=
-fi
 
 
 
@@ -4269,8 +4245,7 @@ config_files="\\
     soqt-config Makefile src/Inventor/Qt/Makefile
     src/Inventor/Qt/common/Makefile src/Inventor/Qt/devices/Makefile
     src/Inventor/Qt/viewers/Makefile src/Inventor/Qt/widgets/Makefile
-    test-code/Makefile test-code/widgets/Makefile examples/Makefile
-    examples/components/Makefile examples/nodes/Makefile"
+    test-code/Makefile test-code/widgets/Makefile"
 config_headers="\\
     config.h"
 
@@ -4323,9 +4298,6 @@ do
   'src/Inventor/Qt/widgets/Makefile' ) CONFIG_FILES="\$CONFIG_FILES src/Inventor/Qt/widgets/Makefile" ;;
   'test-code/Makefile' ) CONFIG_FILES="\$CONFIG_FILES test-code/Makefile" ;;
   'test-code/widgets/Makefile' ) CONFIG_FILES="\$CONFIG_FILES test-code/widgets/Makefile" ;;
-  'examples/Makefile' ) CONFIG_FILES="\$CONFIG_FILES examples/Makefile" ;;
-  'examples/components/Makefile' ) CONFIG_FILES="\$CONFIG_FILES examples/components/Makefile" ;;
-  'examples/nodes/Makefile' ) CONFIG_FILES="\$CONFIG_FILES examples/nodes/Makefile" ;;
   'config.h' ) CONFIG_HEADERS="\$CONFIG_HEADERS config.h" ;;
   # This is an error.
   *) echo "$CONFIG_STATUS: invalid argument: \$ac_option"; exit 1 ;;
@@ -4451,16 +4423,7 @@ s%@uGUI@%$uGUI%;t t
 s%@WIDGET@%$WIDGET%;t t
 s%@EVENT@%$EVENT%;t t
 s%@COMPONENTHEADER@%$COMPONENTHEADER%;t t
-s%@HAVE_RENDERAREA_TRUE@%$HAVE_RENDERAREA_TRUE%;t t
-s%@HAVE_RENDERAREA_FALSE@%$HAVE_RENDERAREA_FALSE%;t t
-s%@HAVE_EXAMINERVIEWER_TRUE@%$HAVE_EXAMINERVIEWER_TRUE%;t t
-s%@HAVE_EXAMINERVIEWER_FALSE@%$HAVE_EXAMINERVIEWER_FALSE%;t t
-s%@HAVE_PLANEVIEWER_TRUE@%$HAVE_PLANEVIEWER_TRUE%;t t
-s%@HAVE_PLANEVIEWER_FALSE@%$HAVE_PLANEVIEWER_FALSE%;t t
-s%@HAVE_WALKVIEWER_TRUE@%$HAVE_WALKVIEWER_TRUE%;t t
-s%@HAVE_WALKVIEWER_FALSE@%$HAVE_WALKVIEWER_FALSE%;t t
-s%@HAVE_FLYVIEWER_TRUE@%$HAVE_FLYVIEWER_TRUE%;t t
-s%@HAVE_FLYVIEWER_FALSE@%$HAVE_FLYVIEWER_FALSE%;t t
+s%@subdirs@%$subdirs%;t t
 CEOF
 
 EOF
@@ -4776,6 +4739,108 @@ trap 'exit 1' 1 2 15
 
 
 test "$no_create" = yes || $SHELL $CONFIG_STATUS || exit 1
+
+#
+# CONFIG_SUBDIRS section.
+#
+if test "$no_recursion" != yes; then
+
+  # Remove --cache-file and --srcdir arguments so they do not pile up.
+  ac_sub_configure_args=
+  ac_prev=
+  for ac_arg in $ac_configure_args; do
+    if test -n "$ac_prev"; then
+      ac_prev=
+      continue
+    fi
+    case "$ac_arg" in
+    -cache-file | --cache-file | --cache-fil | --cache-fi \
+    | --cache-f | --cache- | --cache | --cach | --cac | --ca | --c)
+      ac_prev=cache_file ;;
+    -cache-file=* | --cache-file=* | --cache-fil=* | --cache-fi=* \
+    | --cache-f=* | --cache-=* | --cache=* | --cach=* | --cac=* | --ca=* | --c=*)
+      ;;
+    -srcdir | --srcdir | --srcdi | --srcd | --src | --sr)
+      ac_prev=srcdir ;;
+    -srcdir=* | --srcdir=* | --srcdi=* | --srcd=* | --src=* | --sr=*)
+      ;;
+    *) ac_sub_configure_args="$ac_sub_configure_args $ac_arg" ;;
+    esac
+  done
+
+  ac_given_INSTALL="$INSTALL"
+
+  for ac_config_dir in examples; do
+
+    # Do not complain, so a configure script can configure whichever
+    # parts of a large source tree are present.
+    if test ! -d $srcdir/$ac_config_dir; then
+      continue
+    fi
+
+    echo configuring in $ac_config_dir
+
+    case "$srcdir" in
+    .) ;;
+    *)
+      if test -d ./$ac_config_dir || mkdir ./$ac_config_dir; then :;
+      else
+        { echo "configure: error: cannot create \`pwd\`/$ac_config_dir" 1>&2; exit 1; }
+      fi
+      ;;
+    esac
+
+    ac_popdir=`pwd`
+    cd $ac_config_dir
+
+      # A "../" for each directory in /$ac_config_dir.
+      ac_dots=`echo $ac_config_dir|sed -e 's%^\./%%' -e 's%[^/]$%&/%' -e 's%[^/]*/%../%g'`
+
+    case "$srcdir" in
+    .) # No --srcdir option.  We are building in place.
+      ac_sub_srcdir=$srcdir ;;
+    /*) # Absolute path.
+      ac_sub_srcdir=$srcdir/$ac_config_dir ;;
+    *) # Relative path.
+      ac_sub_srcdir=$ac_dots$srcdir/$ac_config_dir ;;
+    esac
+
+    # Check for guested configure; otherwise get Cygnus style configure.
+    if test -f $ac_sub_srcdir/configure; then
+      ac_sub_configure="$SHELL $ac_sub_srcdir/configure"
+    elif test -f $ac_sub_srcdir/configure.in; then
+      ac_sub_configure=$ac_configure
+    else
+      echo "configure: warning: no configuration information is in $ac_config_dir" 1>&2
+      ac_sub_configure=
+    fi
+
+    # The recursion is here.
+    if test -n "$ac_sub_configure"; then
+
+      # Make the cache file name correct relative to the subdirectory.
+      case "$cache_file" in
+      /*) ac_sub_cache_file=$cache_file ;;
+      *) # Relative path.
+        ac_sub_cache_file="$ac_dots$cache_file" ;;
+      esac
+  case "$ac_given_INSTALL" in
+        [/$]*) INSTALL="$ac_given_INSTALL" ;;
+        *) INSTALL="$ac_dots$ac_given_INSTALL" ;;
+        esac
+
+      echo "running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir"
+      # The eval makes quoting arguments work.
+      if eval $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir
+      then :
+      else
+        { echo "configure: error: $ac_sub_configure failed for $ac_config_dir" 1>&2; exit 1; }
+      fi
+    fi
+
+    cd $ac_popdir
+  done
+fi
 
 
 echo ""
