Bugfix.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9558,15 +9558,19 @@ exec_prefix=$sim_ac_save_exec_prefix
 # default value
 SOQT_STATIC=false
 
-case $enable_static in
-yes | true)  SOQT_STATIC=true;;
-*)           SOQT_STATIC=false;;
-esac
+if test x${enable_shared+set} = xset; then
+  case $enable_shared in
+  yes | true)  SOQT_STATIC=false ;;
+  *)           SOQT_STATIC=true ;;
+  esac
+fi
 
-case $enable_shared in
-yes | true)  SOQT_STATIC=false;;
-*)           SOQT_STATIC=true;;
-esac
+if test x${enable_static+set} = xset; then
+  case $enable_static in
+  yes | true)  SOQT_STATIC=true ;;
+  *)           SOQT_STATIC=false ;;
+  esac
+fi
 
 LIBFLAGS=
 
@@ -9743,7 +9747,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:9746: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:9750: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -9919,7 +9923,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:9922: error: ambiguous option: $1
+    { { echo "$as_me:9926: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -9938,7 +9942,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:9941: error: unrecognized option: $1
+  -*) { { echo "$as_me:9945: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -10004,7 +10008,7 @@ do
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "default-2" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-2" ;;
   "src/config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS src/config.h" ;;
-  *) { { echo "$as_me:10007: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:10011: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -10298,7 +10302,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:10301: creating $ac_file" >&5
+    { echo "$as_me:10305: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -10316,7 +10320,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:10319: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:10323: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -10329,7 +10333,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:10332: error: cannot find input file: $f" >&5
+           { { echo "$as_me:10336: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -10390,7 +10394,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:10393: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:10397: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -10401,7 +10405,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:10404: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:10408: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -10414,7 +10418,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:10417: error: cannot find input file: $f" >&5
+           { { echo "$as_me:10421: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -10531,7 +10535,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:10534: $ac_file is unchanged" >&5
+      { echo "$as_me:10538: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
