Bootstrap.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -10511,7 +10511,7 @@ fi;
 if test x"$with_opengl" != xno; then
 
   if test x"$with_opengl" != xyes && test x"$with_opengl" != x""; then
-    sim_ac_ogl_ldflags=-I$with_opengl/lib
+    sim_ac_ogl_ldflags=-L$with_opengl/lib
     # $sim_ac_ogl_cppflags is set up in the SIM_AC_CHECK_HEADER_GL
     # invocation further below.
   else
@@ -10519,7 +10519,7 @@ if test x"$with_opengl" != xno; then
     # at this location.
     sim_ac_gl_hpux=/opt/graphics/OpenGL
     if test -d $sim_ac_gl_hpux; then
-      sim_ac_ogl_ldflags=-I$sim_ac_gl_hpux/lib
+      sim_ac_ogl_ldflags=-L$sim_ac_gl_hpux/lib
     fi
   fi
 
@@ -10617,9 +10617,10 @@ echo "$as_me:$LINENO: checking how to include gl.h" >&5
 echo $ECHO_N "checking how to include gl.h... $ECHO_C" >&6
 if test x"$with_opengl" != x"no"; then
   sim_ac_gl_save_CPPFLAGS=$CPPFLAGS
+  sim_ac_gl_cppflags=
+
   if test x"$with_opengl" != xyes && test x"$with_opengl" != x""; then
     sim_ac_gl_cppflags="-I${with_opengl}/include"
-    CPPFLAGS="$CPPFLAGS $sim_ac_gl_cppflags"
   else
     # On HP-UX platforms, OpenGL headers and libraries are usually installed
     # at this location.
@@ -10628,6 +10629,9 @@ if test x"$with_opengl" != x"no"; then
       sim_ac_gl_cppflags=-I$sim_ac_gl_hpux/include
     fi
   fi
+
+  CPPFLAGS="$CPPFLAGS $sim_ac_gl_cppflags"
+
 
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
@@ -11023,10 +11027,21 @@ echo "$as_me:$LINENO: checking how to include glu.h" >&5
 echo $ECHO_N "checking how to include glu.h... $ECHO_C" >&6
 if test x"$with_opengl" != x"no"; then
   sim_ac_glu_save_CPPFLAGS=$CPPFLAGS
+  sim_ac_glu_cppflags=
+
   if test x"$with_opengl" != xyes && test x"$with_opengl" != x""; then
     sim_ac_glu_cppflags="-I${with_opengl}/include"
-    CPPFLAGS="$CPPFLAGS $sim_ac_glu_cppflags"
+  else
+    # On HP-UX platforms, OpenGL headers and libraries are usually installed
+    # at this location.
+    sim_ac_gl_hpux=/opt/graphics/OpenGL
+    if test -d $sim_ac_gl_hpux; then
+      sim_ac_glu_cppflags=-I$sim_ac_gl_hpux/include
+    fi
   fi
+
+  CPPFLAGS="$CPPFLAGS $sim_ac_glu_cppflags"
+
 
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
@@ -11118,102 +11133,7 @@ fi
 
 
 
-  sim_ac_gl_hpux=/opt/graphics/OpenGL
-  if test x$sim_ac_glu_header_avail = xfalse && test -d $sim_ac_gl_hpux; then
-    sim_ac_glu_cppflags=-I$sim_ac_gl_hpux/include
-    CPPFLAGS="$CPPFLAGS $sim_ac_glu_cppflags"
 
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-#include <GL/glu.h>
-_ACEOF
-if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
-  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
-  ac_status=$?
-  egrep -v '^ *\+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } >/dev/null; then
-  if test -s conftest.err; then
-    ac_cpp_err=$ac_cxx_preproc_warn_flag
-  else
-    ac_cpp_err=
-  fi
-else
-  ac_cpp_err=yes
-fi
-if test -z "$ac_cpp_err"; then
-  ac_cv_header_GL_glu_h=yes
-else
-  echo "$as_me: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  ac_cv_header_GL_glu_h=no
-fi
-rm -f conftest.err conftest.$ac_ext
-if test $ac_cv_header_GL_glu_h = yes; then
-
-      sim_ac_glu_header_avail=true
-      sim_ac_glu_header=GL/glu.h
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_GL_GLU_H 1
-_ACEOF
-
-
-else
-
-
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-#include <OpenGL/glu.h>
-_ACEOF
-if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
-  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
-  ac_status=$?
-  egrep -v '^ *\+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } >/dev/null; then
-  if test -s conftest.err; then
-    ac_cpp_err=$ac_cxx_preproc_warn_flag
-  else
-    ac_cpp_err=
-  fi
-else
-  ac_cpp_err=yes
-fi
-if test -z "$ac_cpp_err"; then
-  ac_cv_header_OpenGL_glu_h=yes
-else
-  echo "$as_me: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  ac_cv_header_OpenGL_glu_h=no
-fi
-rm -f conftest.err conftest.$ac_ext
-if test $ac_cv_header_OpenGL_glu_h = yes; then
-
-        sim_ac_glu_header_avail=true
-        sim_ac_glu_header=OpenGL/glu.h
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_OPENGL_GLU_H 1
-_ACEOF
-
-
-fi
-
-
-
-
-fi
-
-
-
-  fi
   CPPFLAGS="$sim_ac_glu_save_CPPFLAGS"
   if $sim_ac_glu_header_avail; then
     if test x"$sim_ac_glu_cppflags" = x""; then
@@ -11763,9 +11683,10 @@ echo "$as_me:$LINENO: checking how to include gl.h" >&5
 echo $ECHO_N "checking how to include gl.h... $ECHO_C" >&6
 if test x"$with_opengl" != x"no"; then
   sim_ac_gl_save_CPPFLAGS=$CPPFLAGS
+  sim_ac_gl_cppflags=
+
   if test x"$with_opengl" != xyes && test x"$with_opengl" != x""; then
     sim_ac_gl_cppflags="-I${with_opengl}/include"
-    CPPFLAGS="$CPPFLAGS $sim_ac_gl_cppflags"
   else
     # On HP-UX platforms, OpenGL headers and libraries are usually installed
     # at this location.
@@ -11774,6 +11695,9 @@ if test x"$with_opengl" != x"no"; then
       sim_ac_gl_cppflags=-I$sim_ac_gl_hpux/include
     fi
   fi
+
+  CPPFLAGS="$CPPFLAGS $sim_ac_gl_cppflags"
+
 
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
@@ -12969,49 +12893,8 @@ fi
 echo "$as_me: WARNING: the \`\`moc'' Qt pre-processor tool not found" >&2;}
   else
 
-  if test "${ac_cv_header_qglobal_h+set}" = set; then
-  echo "$as_me:$LINENO: checking for qglobal.h" >&5
-echo $ECHO_N "checking for qglobal.h... $ECHO_C" >&6
-if test "${ac_cv_header_qglobal_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-fi
-echo "$as_me:$LINENO: result: $ac_cv_header_qglobal_h" >&5
-echo "${ECHO_T}$ac_cv_header_qglobal_h" >&6
-else
-  # Is the header compilable?
-echo "$as_me:$LINENO: checking qglobal.h usability" >&5
-echo $ECHO_N "checking qglobal.h usability... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-$ac_includes_default
-#include <qglobal.h>
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_header_compiler=yes
-else
-  echo "$as_me: failed program was:" >&5
-cat conftest.$ac_ext >&5
-ac_header_compiler=no
-fi
-rm -f conftest.$ac_objext conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
-echo "${ECHO_T}$ac_header_compiler" >&6
+  sim_ac_qglobal=false
 
-# Is the header present?
-echo "$as_me:$LINENO: checking qglobal.h presence" >&5
-echo $ECHO_N "checking qglobal.h presence... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
@@ -13034,49 +12917,60 @@ else
   ac_cpp_err=yes
 fi
 if test -z "$ac_cpp_err"; then
-  ac_header_preproc=yes
+  ac_cv_header_qglobal_h=yes
 else
   echo "$as_me: failed program was:" >&5
   cat conftest.$ac_ext >&5
-  ac_header_preproc=no
+  ac_cv_header_qglobal_h=no
 fi
 rm -f conftest.err conftest.$ac_ext
-echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
-echo "${ECHO_T}$ac_header_preproc" >&6
-
-# So?  What about this header?
-case $ac_header_compiler:$ac_header_preproc in
-  yes:no )
-    { echo "$as_me:$LINENO: WARNING: qglobal.h: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: qglobal.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: qglobal.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: qglobal.h: proceeding with the preprocessor's result" >&2;};;
-  no:yes )
-    { echo "$as_me:$LINENO: WARNING: qglobal.h: present but cannot be compiled" >&5
-echo "$as_me: WARNING: qglobal.h: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: qglobal.h: check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: qglobal.h: check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: qglobal.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: qglobal.h: proceeding with the preprocessor's result" >&2;};;
-esac
-echo "$as_me:$LINENO: checking for qglobal.h" >&5
-echo $ECHO_N "checking for qglobal.h... $ECHO_C" >&6
-if test "${ac_cv_header_qglobal_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_cv_header_qglobal_h=$ac_header_preproc
-fi
-echo "$as_me:$LINENO: result: $ac_cv_header_qglobal_h" >&5
-echo "${ECHO_T}$ac_cv_header_qglobal_h" >&6
-
-fi
 if test $ac_cv_header_qglobal_h = yes; then
   sim_ac_qglobal=true
 else
-  { echo "$as_me:$LINENO: WARNING: header file qglobal.h not found" >&5
-echo "$as_me: WARNING: header file qglobal.h not found" >&2;}
-                   sim_ac_qglobal=false
+  # Debian Linux has the Qt-dev installation headers in a separate subdir.
+    sim_ac_debian_qtheaders=/usr/include/qt
+     if test -d $sim_ac_debian_qtheaders; then
+       sim_ac_qt_incflags="-I$sim_ac_debian_qtheaders $sim_ac_qt_incflags"
+       CPPFLAGS="-I$sim_ac_debian_qtheaders $CPPFLAGS"
+
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+#include <qglobal.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  egrep -v '^ *\+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_cxx_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
 fi
+if test -z "$ac_cpp_err"; then
+  ac_cv_header_qglobal_h=yes
+else
+  echo "$as_me: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  ac_cv_header_qglobal_h=no
+fi
+rm -f conftest.err conftest.$ac_ext
+if test $ac_cv_header_qglobal_h = yes; then
+  sim_ac_qglobal=true
+fi
+
+
+
+     fi
+fi
+
 
 
 
@@ -13338,7 +13232,10 @@ echo "${ECHO_T}$sim_ac_qt_cppflags $sim_ac_qt_libs" >&6
     fi
   fi
 
-  fi # sim_ac_qglobal = TRUE
+  else # sim_ac_qglobal = false
+   { echo "$as_me:$LINENO: WARNING: header file qglobal.h not found, can not compile Qt code" >&5
+echo "$as_me: WARNING: header file qglobal.h not found, can not compile Qt code" >&2;}
+  fi
   fi # MOC = false
 
   if test ! x"$sim_ac_qt_libs" = xUNRESOLVED; then
