configure test for QApplication::hadPendingEvents(). Bootstrap.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -25778,6 +25778,60 @@ _ACEOF
 fi
 
 
+echo "$as_me:$LINENO: checking whether QApplication::hasPendingEvents() is available" >&5
+echo $ECHO_N "checking whether QApplication::hasPendingEvents() is available... $ECHO_C" >&6
+if test "${sim_cv_def_qapplication_haspendingevents+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <qapplication.h>
+int
+main ()
+{
+int argc; char ** argv; QApplication app(argc, argv); (void) app.hasPendingEvents();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  sim_cv_def_qapplication_haspendingevents=true
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+sim_cv_def_qapplication_haspendingevents=false
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $sim_cv_def_qapplication_haspendingevents" >&5
+echo "${ECHO_T}$sim_cv_def_qapplication_haspendingevents" >&6
+
+if $sim_cv_def_qapplication_haspendingevents; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_QAPPLICATION_HASPENDINGEVENTS 1
+_ACEOF
+
+fi
+
+
 # QStyleFactory was added in Qt 3.0.
 
 for ac_header in qstylefactory.h
