Mac OS X .app-directory setup

diff --git a/soqt-config b/soqt-config
--- a/soqt-config
+++ b/soqt-config
@@ -12,8 +12,15 @@ me=`echo "$0" | sed 's,^.*[/\\],,g'`
 wd=`echo "$0" | sed 's,/[^/]*$,,'`
 prefix=`cd "$wd"/..; pwd` 
 
-# sed script replacing "fmt -w76 | sed '2,$ s/^/  /g; $ q; 1,$ s/$/ \\/'"
-format='/^............................................................................./ {
+hello=`echo hello | fmt -t -w70 2>&1`
+if test x"$hello" = x"hello"; then
+  # 'fmt -t' works
+  preformat="fmt -t -w76"
+  sedformat='$ q; s/$/ \\/'
+else
+  # sed script replacing "fmt -w76 | sed '2,$ s/^/  /g; $ q; 1,$ s/$/ \\/'"
+  preformat="cat"
+  sedformat='/^............................................................................./ {
   G
   s/^\([^\
 ]\{1,76\}\) \(.*\)\(\
@@ -21,6 +28,7 @@ format='/^......................................................................
   P
   D
 }'
+fi
 
 usage="\
 Usage: $me [OPTIONS]
@@ -136,7 +144,7 @@ do
             ;;
           *)
             echo $compiler $CPPFLAGS $cppflags $CXXFLAGS $cxxflags -c $1 \
-              | sed "$format"
+              | $preformat | sed "$sedformat"
             $compiler \
               $CPPFLAGS $cppflags \
               $CXXFLAGS $cxxflags \
@@ -159,13 +167,30 @@ do
       progname=$1
       shift
       echo $compiler $LDFLAGS $ldflags -o $progname $@ $libs $LIBS \
-        | sed "$format"
+        | $preformat | sed "$sedformat"
       $compiler \
         $LDFLAGS $ldflags \
         -o $progname $@ \
         $libs $LIBS
       retval=$?
       test $retval -ne 0 && exit $retval
+      case $host in
+      *-darwin*)
+        echo "$me: making Mac OS X application"
+        mkdir $progname.app 2>/dev/null
+        mkdir $progname.app/Contents 2>/dev/null
+        mkdir $progname.app/Contents/MacOS 2>/dev/null
+        if test -d $progname.app/Contents/MacOS &&
+          mv -f $progname $progname.app/Contents/MacOS/ &&
+          echo "APPL????" >$progname.app/Contents/PkgInfo; then
+          :
+        else
+          echo >&2 "$me: failed to make Mac OS X application"
+          echo >&2 " - problem is probably user permission or disk space related"
+          exit 1
+        fi
+        ;;
+      esac
       exit 0
       ;;
     --build)
@@ -209,7 +234,7 @@ do
       echo $compiler $CPPFLAGS $cppflags $CXXFLAGS $cxxflags \
         $LDFLAGS $ldflags $extraldflags \
         -o $progname $objs $extralibs $libs $LIBS \
-        | sed "$format"
+        | $preformat | sed "$sedformat"
       $compiler \
         $CPPFLAGS $cppflags \
         $CXXFLAGS $cxxflags \
@@ -218,6 +243,23 @@ do
         $extralibs $libs $LIBS
       retval=$?
       test $retval -ne 0 && exit $retval
+      case $host in
+      *-darwin*)
+        echo "$me: making Mac OS X application"
+        mkdir $progname.app 2>/dev/null
+        mkdir $progname.app/Contents 2>/dev/null
+        mkdir $progname.app/Contents/MacOS 2>/dev/null
+        if test -d $progname.app/Contents/MacOS &&
+          mv -f $progname $progname.app/Contents/MacOS/ &&
+          echo "APPL????" >$progname.app/Contents/PkgInfo; then
+          :
+        else
+          echo >&2 "$me: failed to make Mac OS X application"
+          echo >&2 " - problem is probably user permission or disk space related"
+          exit 1
+        fi
+        ;;
+      esac
       exit 0
       ;;
     # ignore some options
